In [1]:
# Import Libraries

import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("/content/Salary_Data.csv")

In [3]:
data.head()

YearsExperience  Salary
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891

In [4]:
# Assigh X and Y values

x=data[["YearsExperience"]]
x


YearsExperience
0               1.1
1               1.3
2               1.5
3               2.0
4               2.2
5               2.9
6               3.0
7               3.2
8               3.2
9               3.7
10              3.9
11              4.0
12              4.0
13              4.1
14              4.5
15              4.9
16              5.1
17              5.3
18              5.9
19              6.0
20              6.8
21              7.1
22              7.9
23              8.2
24              8.7
25              9.0
26              9.5
27              9.6
28             10.3
29             10.5

In [5]:
y=data[["Salary"]]
y

Salary
0    39343
1    46205
2    37731
3    43525
4    39891
5    56642
6    60150
7    54445
8    64445
9    57189
10   63218
11   55794
12   56957
13   57081
14   61111
15   67938
16   66029
17   83088
18   81363
19   93940
20   91738
21   98273
22  101302
23  113812
24  109431
25  105582
26  116969
27  112635
28  122391
29  121872

In [6]:
# Using sk learn to split datas

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

x_train


YearsExperience
28             10.3
24              8.7
12              4.0
0               1.1
4               2.2
16              5.1
5               2.9
13              4.1
11              4.0
22              7.9
1               1.3
2               1.5
25              9.0
3               2.0
21              7.1
26              9.5
18              5.9
29             10.5
20              6.8
7               3.2
10              3.9
14              4.5
19              6.0
6               3.0

In [7]:
# standard scalar for distance base

from sklearn.preprocessing import StandardScaler
scalar=StandardScaler()
x_train=scalar.fit_transform(x_train)
x_test=scalar.fit_transform(x_test)

In [8]:
x_train

array([[ 1.77445774],
       [ 1.21912622],
       [-0.41216011],
       [-1.41869849],
       [-1.03690807],
       [-0.03036969],
       [-0.79395053],
       [-0.37745189],
       [-0.41216011],
       [ 0.94146047],
       [-1.34928205],
       [-1.27986561],
       [ 1.32325088],
       [-1.10632451],
       [ 0.66379471],
       [ 1.49679198],
       [ 0.24729607],
       [ 1.84387418],
       [ 0.55967005],
       [-0.68982587],
       [-0.44686833],
       [-0.23861901],
       [ 0.28200429],
       [-0.75924231]])

In [9]:
# support vector regression

from sklearn.svm import SVR
model=SVR()

model.fit(x_train,y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [10]:
y_pred=model.predict(x_test)
y_pred

array([62175.07239017, 62163.90530794, 62175.99958482, 62165.8135171 ,
       62160.44074665, 62160.50273428])

In [11]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error


mse = mean_squared_error(y_test, y_pred)
mse

952248990.0704432

In [19]:
r2=r2_score(y_test,y_pred)
r2

-0.8642454037325169

In [20]:
import pickle

In [14]:
file_name="salary.sav"

In [15]:
pickle.dump(model,open(file_name,"wb"))

In [16]:
load=pickle.load(open("/content/salary.sav","rb"))

In [23]:
result=load.predict([[18]])

In [24]:
result

array([62168.76120633])